/**
 * Demo bootstrap for the HTML report renderer.
 *
 * Until investigate.ts exists, this module synthesizes a realistic
 * Investigation / Verification / EvidenceItem[] / TimelineEvent[] set for
 * case-01-demo and writes two reports to disk:
 *   - report/case-01-demo.html           (VERIFIED stamp)
 *   - report/case-01-demo.rejected.html  (REJECTED stamp + verifier objections)
 *
 * This proves the renderer contract end-to-end and gives the demo video its
 * stamp-flip beat. Once the real workflow lands, this file can be deleted and
 * the renderer called directly from investigate.ts / index.ts.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type {
  EvidenceItem,
  Investigation,
  TimelineEvent,
  Verification,
} from "../schemas/investigation.js";
import { renderHtmlReport } from "./render-html.js";

const caseId = "case-01-demo";

const evidence: EvidenceItem[] = [
  {
    id: "EVD-01",
    source: "orders.csv",
    type: "orders",
    timestamp: "2026-08-27T10:20:00Z",
    statement: "Order ORD-2847 created for CUST-A",
    ref: "ORD-2847",
    parties: ["CUST-A"],
    raw: "Order ORD-2847 created for CUST-A",
  },
  {
    id: "EVD-02",
    source: "orders.csv",
    type: "orders",
    timestamp: "2026-08-27T11:49:00Z",
    statement: "Order ORD-2993 created for CUST-B",
    ref: "ORD-2993",
    parties: ["CUST-B"],
    raw: "Order ORD-2993 created for CUST-B",
  },
  {
    id: "EVD-03",
    source: "payment_provider.csv",
    type: "payment",
    timestamp: "2026-08-27T10:32:00Z",
    statement: "TXN-773 for CUST-A / ORD-2847, amount 250000, status FAILED",
    ref: "TXN-773",
    parties: ["CUST-A"],
    amountMinor: 25000000,
    status: "failed",
    raw: "TXN-773 recorded as FAILED",
  },
  {
    id: "EVD-04",
    source: "payment_provider.csv",
    type: "payment",
    timestamp: "2026-08-27T11:47:00Z",
    statement: "TXN-774 for CUST-B / ORD-2993, amount 250000, status SUCCESSFUL",
    ref: "TXN-774",
    parties: ["CUST-B"],
    amountMinor: 25000000,
    status: "success",
    raw: "TXN-774 recorded as SUCCESSFUL",
  },
  {
    id: "EVD-05",
    source: "customer_chat.txt",
    type: "chat",
    timestamp: "2026-08-27T10:31:00Z",
    statement: "Customer A claims payment was made",
    raw: "Customer A claims payment was made",
  },
  {
    id: "EVD-06",
    source: "receipt.txt",
    type: "receipt",
    timestamp: "2026-08-27T10:30:00Z",
    statement:
      "Receipt submitted by CUST-A shows TXN-773 as SUCCESSFUL - conflicts with provider record",
    ref: "TXN-773",
    parties: ["CUST-A"],
    raw: "Receipt shows TXN-773 as SUCCESSFUL",
  },
];

const timeline: TimelineEvent[] = [
  {
    timestamp: "2026-08-27T10:20:00Z",
    event: "Order ORD-2847 created (CUST-A)",
    evidenceId: "EVD-01",
    importance: "medium",
  },
  {
    timestamp: "2026-08-27T10:32:00Z",
    event: "TXN-773 recorded as FAILED by provider",
    evidenceId: "EVD-03",
    importance: "high",
  },
  {
    timestamp: "2026-08-27T10:31:00Z",
    event: "Customer A claims payment was made",
    evidenceId: "EVD-05",
    importance: "medium",
  },
  {
    timestamp: "2026-08-27T11:49:00Z",
    event: "Order ORD-2993 created (CUST-B)",
    evidenceId: "EVD-02",
    importance: "medium",
  },
  {
    timestamp: "2026-08-27T11:47:00Z",
    event: "TXN-774 recorded as SUCCESSFUL by provider",
    evidenceId: "EVD-04",
    importance: "high",
  },
];

const investigation: Investigation = {
  caseId,
  disputedCustomer: "CUST-A",
  claimIsValid: false,
  verifiedCustomer: "CUST-B",
  confidence: 0.96,
  conclusion:
    "Customer A's payment claim is NOT verified. The successful ₦250,000 transaction belongs to Customer B, not Customer A.",
  keyFinding:
    "The successful ₦250,000 transaction (TXN-774) belongs to Customer B.",
  findings: [
    "Customer A's transaction (TXN-773) was recorded as FAILED by the payment provider at 10:32 UTC.",
    "Customer A's submitted receipt claims TXN-773 was successful, directly contradicting the provider record.",
    "The only successful transaction of matching amount (₦250,000) around this period is TXN-774, tied to Customer B's order (ORD-2993).",
    "No settlement record exists tying TXN-773 to any completed bank settlement.",
  ],
  contradictions: [
    "Receipt (EVD-06) states TXN-773 was successful; provider record (EVD-03) states TXN-773 failed.",
  ],
  supportingEvidenceIds: ["EVD-03", "EVD-04", "EVD-06"],
  unresolvedQuestions: [
    "Whether the receipt was fabricated or generated by an intermediary system in error has not been established.",
  ],
};

/** Approved verdict — VERIFIED stamp. */
const verified: Verification = {
  approved: true,
  reasoning:
    "Provider and bank settlement records independently agree TXN-773 failed and TXN-774 (CUST-B) is the only matching successful transaction.",
  confidence: 0.94,
  unsupportedClaims: [],
  missingEvidence: [],
  contradictionErrors: [],
};

/** Rejected verdict — REJECTED stamp + verifier objections panel. */
const rejected: Verification = {
  approved: false,
  reasoning:
    "The investigator's conclusion did not fully reconcile the receipt against the provider record.",
  confidence: 0.4,
  correctedConclusion:
    "Insufficient evidence to confirm which customer's ₦250,000 payment is valid; the receipt cannot be independently verified. Flag for manual review.",
  unsupportedClaims: [
    "Claim the receipt can be trusted as primary evidence is asserted, not supported by any settlement record.",
  ],
  missingEvidence: [
    "No bank settlement record for CUST-A's claimed charge.",
    "No confirmation that the ₦250,000 charge hit CUST-A's account.",
  ],
  contradictionErrors: [
    "Receipt (EVD-06) status SUCCESSFUL contradicts provider record (EVD-03) status FAILED and was not resolved.",
  ],
};

function write(caseId: string, suffix: string, input: Parameters<typeof renderHtmlReport>[0]) {
  const dir = join("report");
  mkdirSync(dir, { recursive: true });
  const file = join(dir, `${caseId}${suffix}.html`);
  writeFileSync(file, renderHtmlReport(input), "utf8");
  console.log(`wrote ${file}`);
}

export function renderDemoReports(): void {
  write(caseId, "", {
    caseId,
    investigation,
    verification: verified,
    evidence,
    timeline,
  });
  write(caseId, ".rejected", {
    caseId,
    investigation,
    verification: rejected,
    evidence,
    timeline,
    wasRetried: true,
  });
}

// Invoked when run directly via `npm run report:demo`.
if (process.argv[1]?.endsWith("bootstrap-demo.ts")) {
  renderDemoReports();
}
